-- MySQL Script generated by MySQL Workbench
-- dom 02 mar 2025 12:20:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema emprestai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emprestai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emprestai` ;
USE `emprestai` ;

-- -----------------------------------------------------
-- Table `emprestai`.`tipo_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestai`.`tipo_clientes` (
  `id_tipo_cliente` INT NOT NULL AUTO_INCREMENT,
  `dsc_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestai`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestai`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(90) NOT NULL,
  `score` INT NOT NULL,
  `tp_cliente` INT NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `renda_m_liq` DECIMAL(10,2) NOT NULL,
  `renda_familia_liq` DECIMAL(10,2) NOT NULL,
  `qtde_pess_familia` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `id_tipo_cliente_clientes_idx` (`tp_cliente` ASC) VISIBLE,
  CONSTRAINT `id_tipo_cliente_clientes`
    FOREIGN KEY (`tp_cliente`)
    REFERENCES `emprestai`.`tipo_clientes` (`id_tipo_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestai`.`motivo_encerramentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestai`.`motivo_encerramentos` (
  `id_motivo_encerramento` INT NOT NULL AUTO_INCREMENT,
  `dsc_encerramento` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_motivo_encerramento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestai`.`status_emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestai`.`status_emprestimos` (
  `id_status_emp` INT NOT NULL AUTO_INCREMENT,
  `desc_status_emp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status_emp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestai`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestai`.`servicos` (
  `id_servico` INT NOT NULL AUTO_INCREMENT,
  `desc_servico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestai`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestai`.`emprestimos` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `valor_emprestimo` DECIMAL(10,2) NOT NULL,
  `qtde_parcelas` INT NOT NULL,
  `tx_juros` DECIMAL(5,2) NOT NULL,
  `dt_inicio` DATE NOT NULL,
  `id_status_emp` INT NOT NULL,
  `id_tipo_emp` INT NOT NULL,
  `custo_seguro` DECIMAL(10,2) NOT NULL,
  `valor_IOF` DECIMAL(10,2) NOT NULL,
  `outros_custos` DECIMAL(10,2) NULL DEFAULT NULL,
  `dt_contratacao` DATE NOT NULL,
  `id_motivo_enc` INT NOT NULL,
  `juros_mora` DECIMAL(5,2) NOT NULL,
  `taxa_multa` DECIMAL(5,2) NOT NULL,
  `id_emp_origem` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `cpfCliente_emprestimos_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `tipoServico_emprestimos_idx` (`id_tipo_emp` ASC) VISIBLE,
  INDEX `statusEmprestimo_emprestimos_idx` (`id_status_emp` ASC) INVISIBLE,
  INDEX `motivos_encerramentos_Emprestimos_idx` (`id_motivo_enc` ASC) VISIBLE,
  INDEX `contrato_refinanciado_idx` (`id_emp_origem` ASC) VISIBLE,
  CONSTRAINT `contrato_refinanciado`
    FOREIGN KEY (`id_emp_origem`)
    REFERENCES `emprestai`.`emprestimos` (`id_emprestimo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `id_cliente_emp`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `emprestai`.`clientes` (`id_cliente`),
  CONSTRAINT `motivos_enc_emp`
    FOREIGN KEY (`id_motivo_enc`)
    REFERENCES `emprestai`.`motivo_encerramentos` (`id_motivo_encerramento`),
  CONSTRAINT `statusEmp_emp`
    FOREIGN KEY (`id_status_emp`)
    REFERENCES `emprestai`.`status_emprestimos` (`id_status_emp`),
  CONSTRAINT `tpServico_emp`
    FOREIGN KEY (`id_tipo_emp`)
    REFERENCES `emprestai`.`servicos` (`id_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = REDUNDANT;


-- -----------------------------------------------------
-- Table `emprestai`.`status_parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestai`.`status_parcelas` (
  `id_status_parcelas` INT NOT NULL AUTO_INCREMENT,
  `desc_status_parcelas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status_parcelas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestai`.`parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestai`.`parcelas` (
  `id_parcela` INT NOT NULL AUTO_INCREMENT,
  `id_emprestimo` INT NOT NULL,
  `n_parcela` INT NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  `dt_vencimento` DATE NOT NULL,
  `dt_pagamento` DATE NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id_parcela`),
  INDEX `emprestimo_parcela_idx` (`id_emprestimo` ASC) VISIBLE,
  INDEX `statusParcelas_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `emprestimo_parcela`
    FOREIGN KEY (`id_emprestimo`)
    REFERENCES `emprestai`.`emprestimos` (`id_emprestimo`),
  CONSTRAINT `statusParcelas`
    FOREIGN KEY (`id_status`)
    REFERENCES `emprestai`.`status_parcelas` (`id_status_parcelas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
