db.url=jdbc:mysql://localhost:3306/emprestai
db.username=root
db.password=1234
#pessoal
pess.percentrenda=30
pess.jurosmin=8.49
pess.jurosmax=9.99
pess.valormin=100
pess.valormax=20000
pess.prazomin=6
pess.prazomax=30
pess.idademax=75
pess.carenciamax=30

#consignado
cons.margem=35
cons.jurosmin=1.80
cons.jurosmax=2.14
cons.valormin=1000
cons.prazomin=24
cons.prazomax=92
cons.idademax=80
cons.carenciamax=60

iof=0.38
percentualrefinanciamento=20
percentualjurosmora=0.033
percentualmultaatraso=2